In [1]:
import pandas as pd

## 1. Merging Data

`pd.merge()` joins two DataFrames on a shared column (`subject_id` here), similar to VLOOKUP in Excel or JOIN in databases.

First, create and print the two original tables:

In [2]:
left = pd.DataFrame({
         'id':[1,2,3,4,5],
         'Name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'],
         'subject_id':['sub1','sub2','sub4','sub6','sub5']})
right = pd.DataFrame({
         'id':[1,2,3,4,5],
         'Name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'],
         'subject_id':['sub2','sub4','sub3','sub6','sub5']})
print(left)
print(right)

   id    Name subject_id
0   1    Alex       sub1
1   2     Amy       sub2
2   3   Allen       sub4
3   4   Alice       sub6
4   5  Ayoung       sub5
   id   Name subject_id
0   1  Billy       sub2
1   2  Brian       sub4
2   3   Bran       sub3
3   4  Bryce       sub6
4   5  Betty       sub5

Merge on `subject_id` (inner join: only keys present in BOTH tables are kept):

In [3]:
print(pd.merge(left, right, on='subject_id'))

   id_x  Name_x subject_id  id_y Name_y
0     2     Amy       sub2     1  Billy
1     3   Allen       sub4     2  Brian
2     4   Alice       sub6     4  Bryce
3     5  Ayoung       sub5     5  Betty

**Observation**: only 4 rows remain after merging. `sub1` and `sub3` are dropped because each appears in only one of the two tables.

## 2. Grouping Data

`df.groupby('Year')` splits the data into groups by year, and `get_group()` retrieves one of them.

In [4]:
ipl_data = {'Team': ['Riders','Riders','Devils','Devils','Kings','kings',
                     'Kings','Kings','Riders','Royals','Royals','Riders'],
            'Rank': [1,2,2,3,3,4,1,1,2,4,1,2],
            'Year': [2014,2015,2014,2015,2014,2015,2016,2017,2016,2014,2015,2017],
            'Points':[876,789,863,673,741,812,756,788,694,701,804,690]}
df = pd.DataFrame(ipl_data)
df

      Team  Rank  Year  Points
0   Riders     1  2014     876
1   Riders     2  2015     789
2   Devils     2  2014     863
3   Devils     3  2015     673
4    Kings     3  2014     741
5    kings     4  2015     812
6    Kings     1  2016     756
7    Kings     1  2017     788
8   Riders     2  2016     694
9   Royals     4  2014     701
10  Royals     1  2015     804
11  Riders     2  2017     690

In [5]:
grouped = df.groupby('Year')
grouped.get_group(2014)   # retrieve the 2014 group

     Team  Rank  Year  Points
0  Riders     1  2014     876
2  Devils     2  2014     863
4   Kings     3  2014     741
9  Royals     4  2014     701

**Observation**: the 2014 group contains 4 rows (Riders, Devils, Kings, Royals).

## 3. Concatenating Data

`pd.concat()` stacks tables with the same structure along an axis (it does NOT renumber the index).

In [6]:
one = pd.DataFrame({
        'Name': ['Alex','Amy','Allen','Alice','Ayoung'],
        'subject_id':['sub1','sub2','sub4','sub6','sub5'],
        'Marks_scored':[98,90,87,69,78]}, index=[1,2,3,4,5])
two = pd.DataFrame({
        'Name': ['Billy','Brian','Bran','Bryce','Betty'],
        'subject_id':['sub2','sub4','sub3','sub6','sub5'],
        'Marks_scored':[89,80,79,97,88]}, index=[1,2,3,4,5])
print(one)
print(two)

     Name subject_id  Marks_scored
1    Alex       sub1            98
2     Amy       sub2            90
3   Allen       sub4            87
4   Alice       sub6            69
5  Ayoung       sub5            78
    Name subject_id  Marks_scored
1  Billy       sub2            89
2  Brian       sub4            80
3   Bran       sub3            79
4  Bryce       sub6            97
5  Betty       sub5            88

In [7]:
print(pd.concat([one, two]))

     Name subject_id  Marks_scored
1    Alex       sub1            98
2     Amy       sub2            90
3   Allen       sub4            87
4   Alice       sub6            69
5  Ayoung       sub5            78
1   Billy       sub2            89
2   Brian       sub4            80
3    Bran       sub3            79
4   Bryce       sub6            97
5   Betty       sub5            88

**Observation**: the result has 10 rows, with index 1-5 appearing twice, showing that `concat` simply stacks the tables without handling duplicates.

## Summary

| Operation | Function | Purpose |
|---|---|---|
| Merging | `pd.merge()` | Join two tables horizontally on a shared key |
| Grouping | `df.groupby()` | Split data into groups, then operate on each group |
| Concatenating | `pd.concat()` | Stack tables along an axis |